---
- hosts: web
  tasks:
  - name: "Instalar Apache2"
    apt:
      name: apache2
      state: latest
      update_cache: yes
    become: true

  - name: Garantir que o Apache2 esteja rodando
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: true
    become: true

  - name: "Copiar html"
    copy:
      src: "~/app/index.html"
      dest: "~/var/www/html/index.html"
    become: true
    notify: 
      - restart apache2

  handlers:
  - name: restart apache2
    service: apache2
    state: restarted
  become: true
