CREATE DATABASE IF NOT EXISTS IMPACTA_DATABASE;
USE IMPACTA_DATABASE;

CREATE TABLE IF NOT EXISTS CLIENT (
    CLIENT_ID INTEGER NOT NULL PRIMARY KEY,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    CLIENT_CPF NUMERIC(11) NOT NULL,
    CLIENT_CITY VARCHAR(100) NOT NULL,
    CLIENT_STATE VARCHAR(2) NOT NULL,
    CLIENT_CREDIT_LIMIT DECIMAL(7,2) NOT NULL
);

INSERT INTO CLIENT VALUES
(1, 'Dedron', 12312312312, 'Andra', 'XY', 100.00);